package org.jncc.base.statistic;
// default package
// Generated 2015-5-8 20:38:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EStatistic generated by hbm2java
 */
public class EStatistic implements java.io.Serializable {

	private Integer id;
	private Date accessTime;
	private String accessIp;
	private String comment;

	public EStatistic() {
	}

	public EStatistic(Date accessTime) {
		this.accessTime = accessTime;
	}

	public EStatistic(Date accessTime, String accessIp, String comment) {
		this.accessTime = accessTime;
		this.accessIp = accessIp;
		this.comment = comment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getAccessTime() {
		return this.accessTime;
	}

	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

	public String getAccessIp() {
		return this.accessIp;
	}

	public void setAccessIp(String accessIp) {
		this.accessIp = accessIp;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
