package org.jncc.base.statistic;
// default package
// Generated 2015-5-8 20:38:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EUserstatistic generated by hbm2java
 */
public class EUserstatistic implements java.io.Serializable {

	private Integer id;
	private Date time;
	private String ip;
	private String username;
	private String status;
	private String commnet;

	public EUserstatistic() {
	}

	public EUserstatistic(Date time) {
		this.time = time;
	}

	public EUserstatistic(Date time, String ip, String username, String status,
			String commnet) {
		this.time = time;
		this.ip = ip;
		this.username = username;
		this.status = status;
		this.commnet = commnet;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCommnet() {
		return this.commnet;
	}

	public void setCommnet(String commnet) {
		this.commnet = commnet;
	}

}
